1ct best nonce
gmx-io/gmx-interface pull request #1005
Opened 2024-06-10 14:41 UTC by onemicky

2024-06-11 07:28 UTC, gmxer requested changes

2024-06-11 07:28 UTC, gmxer commented on src/lib/contracts/utils.ts
> +    let threshold = 3;
I think logic should be organized the way that each successful request adds another ~1 seconds to a wait time for other requests. And some total limit (5000ms seems fine). For example let's say If I have two requests:

case 1
```
0000ms r1, r2 started
1000ms r1 fulfilled with 2 (wait for another second for a r2)
1500ms r2 fulfilled with 3 
1500ms return 3
```
case 2
```
0000ms r1, r2 started
1000ms r1 fulfilled with 2 (wait for another second for a r2)
2000ms return 2
2500ms r2 fulfilled with 3 
```
case 3
```
0000ms r1, r2 started
5000ms reject with error
```

2024-06-11 07:28 UTC, gmxer commented on src/lib/contracts/utils.ts
> +    let threshold = 3;
please also add some tests with 1,2 and 4 wallets

2024-06-11 07:28 UTC, gmxer commented on src/lib/contracts/utils.ts
> +    let threshold = 3;
also I found a case in current solution that doesn't make sense. It got 2 different nonce but rejected with error:
```
test("weird case", () => {
    const providers: any[] = [
      new MockWallet(1, false, 1),
      new MockWallet(2, true, 4998),
      new MockWallet(3, true, 4999),
    ];
    const res = getBestNonce(providers);
    jest.advanceTimersByTime(5001);
    expect(res).resolves.toBe(2);
  });
```

2024-06-11 11:11 UTC, gdev8317 commented on src/lib/contracts/utils.ts
> +      resolved = true;
a small suggestion, you can clear timeout here, so there will be no need to track `resolved` and check it inside `setResolveTimeout`

2024-06-11 14:15 UTC, onemicky commented on src/lib/contracts/utils.ts
> +        console.log("Nonces been received: ", results);
Sorry for that, it's only for test purposes. Will defenitely remove before merge

2024-06-11 15:57 UTC, gdev8317 commented on src/lib/contracts/utils.ts
> +      resolved = true;
discussed it dm, no need to do this

2024-06-12 04:54 UTC, gmxer approved these changes

2024-06-12 07:04 UTC, merged