Init orders refactoring
gmx-io/gmx-interface pull request #1041
Opened 2024-06-19 11:00 UTC by midas-myth

2024-06-28 17:08 UTC, onemicky requested changes

2024-07-01 11:57 UTC, midas-myth commented on src/components/Exchange/OrdersList.css
> +/* .Orders-list {
removed file, moved remaining rules to shared css

2024-07-01 11:57 UTC, midas-myth commented on src/components/OrderEditorContainer/OrderEditorContainer.tsx
> +    <OrderEditor order={editingOrder} onClose={() => setEditingOrderKey(undefined)} setPendingTxns={setPendingTxns} />
done

2024-07-01 11:57 UTC, midas-myth commented on src/components/Synthetics/OrderList/OrderList.tsx
> +  const areAllOrdersSelected = orders.length > 0 && orders.every((o) => selectedOrdersKeys?.includes(o.key));
done

2024-07-01 11:57 UTC, midas-myth commented on src/components/Synthetics/OrderList/OrderList.tsx
> +              ))}
done the 1 way, i pass a (el, key)=>void handler

2024-07-01 11:57 UTC, midas-myth commented on src/components/Synthetics/PositionItem/PositionItem.tsx
> +  const ordersWarningsList = ordersWithErrors.filter(({ orderErrors }) => orderErrors.level === "warning");
done

2024-07-01 11:57 UTC, midas-myth commented on src/components/Synthetics/PositionItem/PositionItem.tsx
> +            setEditingOrderKey(order.key);
done

2024-07-01 12:14 UTC, onemicky submitted a review, later dismissed

2024-07-01 13:52 UTC, onemicky approved these changes

2024-07-01 14:13 UTC, merged