Ethena listing
gmx-io/gmx-interface pull request #1128
Opened 2024-07-30 14:47 UTC by onemicky

2024-07-30 15:15 UTC, midas-myth requested changes

2024-07-30 15:15 UTC, midas-myth commented on src/config/markets.ts
> +    "0x45aD16Aaa28fb66Ef74d5ca0Ab9751F2817c81a4": DEFAULT_LISTING,
Before merge, lets set these to real values

2024-07-30 20:28 UTC, midas-myth commented on src/config/markets.ts
> +    "0x45aD16Aaa28fb66Ef74d5ca0Ab9751F2817c81a4": DEFAULT_LISTING,
done

2024-07-31 07:38 UTC, gmxer approved these changes

2024-07-31 07:46 UTC, merged