Add additional metrics
gmx-io/gmx-interface pull request #1279
Opened 2024-10-01 01:31 UTC by divhead

- Migrated to batched metrics
- Added metrics for candles loading time
- Added metrics for "trading data" loading time
- Added browser info to all metric events
- Added metrics for Long Tasks duration (JS Blocking time)
- Added metrics for Synthetics Page mount time
- Added metrics for Account info initialization time

2024-10-01 09:36 UTC, gmxer requested changes

2024-10-01 09:36 UTC, gmxer commented on src/components/Synthetics/TVChart/TVChart.tsx
> +let METRICS_IS_FIRST_TIME_LOAD = true;
I think it's weird to name non-constant variables in upper case

2024-10-01 09:36 UTC, gmxer commented on src/lib/metrics/Metrics.ts
> +      this.queue = this.queue.slice(MAX_BATCH_LENGTH - 1);
no need to check `this.queue.length > MAX_BATCH_LENGTH`, just always do this logic

2024-10-02 09:09 UTC, gmxer commented on src/lib/metrics/Metrics.ts
> +      this.queue = this.queue.slice(MAX_BATCH_LENGTH - 1);
not fixed

2024-10-02 09:11 UTC, gmxer commented on src/lib/metrics/Metrics.ts
> +      this.queue = this.queue.slice(MAX_BATCH_LENGTH - 1);
not fixed

2024-10-02 09:14 UTC, gmxer requested changes
some pending changes left

2024-10-02 10:03 UTC, gmxer approved these changes

2024-10-02 14:35 UTC, onemicky approved these changes

2024-10-02 14:46 UTC, merged