updated rainbowkit and wagmi
gmx-io/gmx-interface pull request #1371
Opened 2024-11-08 13:53 UTC by hubert-de-lalye

2024-11-12 13:00 UTC, divhead commented
need to change base to 49

2024-11-12 13:02 UTC, divhead requested changes
base branch + 1 comment

2024-11-14 10:21 UTC, hubert-de-lalye commented
Rebased and fixed

2024-11-14 10:25 UTC, divhead approved these changes

2024-11-14 10:51 UTC, merged