remove link to gmx.io from logo
gmx-io/gmx-interface pull request #287
Opened 2022-08-31 17:11 UTC by vipineth

2022-09-03 12:53 UTC, divhead requested changes

2022-09-03 12:53 UTC, divhead commented on src/App.js
> -          <HeaderLink isHomeLink={true} className="App-header-link-main" to="/">
Oh, after the refactoring, it was moved to src/components/Header. Sorry, but it needs to update by master, and then, ok

2022-09-05 12:50 UTC, divhead submitted a review, later dismissed

2022-09-06 09:29 UTC, gdev8317 approved these changes

2022-09-08 11:07 UTC, closed without merging