migrate subgraphs to Satsuma
gmx-io/gmx-interface pull request #496
Opened 2023-05-18 23:05 UTC by gdev8317

2023-05-20 02:48 UTC, vipineth approved these changes

2023-05-20 02:51 UTC, vipineth requested changes
The referrals page does not seem to show data.

2023-05-22 10:46 UTC, divhead approved these changes

2023-05-22 12:42 UTC, vipineth approved these changes

2023-05-22 12:47 UTC, merged