fix infinite trade redirect
gmx-io/gmx-interface pull request #922
Opened 2024-04-22 14:16 UTC by gmxer

tradePageVersion now only depends on a browser url, not on an internal state, i.e. there's only 1 point of truth.

2024-04-22 18:51 UTC, onemicky requested changes

2024-04-22 18:51 UTC, onemicky commented on src/context/GlobalContext/GlobalContextProvider.tsx
> +  tradePageVersion: any;
let's fix types here

2024-04-23 03:45 UTC, gmxer commented on src/context/GlobalContext/GlobalContextProvider.tsx
> +  tradePageVersion: any;
fixed

2024-04-23 09:00 UTC, onemicky submitted a review, later dismissed

2024-04-23 09:05 UTC, onemicky approved these changes

2024-04-23 09:05 UTC, merged